name: ChatGPT Pull Request Review

on:
  pull_request:
    branches: [ main ]

jobs: 
  buid: 
    runs-on: ubuntu-latest
  
    steps:
    - uses: unsafecoerce/chatgpt-action@release/v2
    - name: ChatGPT Action
    
  
  
