name: ChatGPT Pull Request Review

on:
  pull_request:
    types: [opened, synchronize]

env: 
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs: 
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGPT explain code
    steps:
      - name: ChatGPT explain code
        uses: unsafecoerce/chatgpt-action@release/v2
        with:
          # The action to run, currently can be "review", "score"
          action: review
  
